FROM node:20

EXPOSE 8080

ENV NODE_ENV=development

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm install --legacy-peer-deps

# Cài đặt Docker CLI trong container NestJS
RUN apt-get update && apt-get install -y docker.io

# Bundle app source
COPY . .

RUN npm run build

CMD [ "node", "dist/src/main.js" ]
