export const Keys = {
  LOGO_URL: 'LOGO_URL',
  SYSTEM_NAME: 'SYSTEM_NAME',
  LOGIN_URL: 'LOGIN_URL',
  DEFAULT_TEMPLATE_SPECIFICATION: 'DEFAULT_TEMPLATE_SPECIFICATION',
  DEFAULT_FILE_PATHS: 'DEFAULT_FILE_PATHS',
  DEFAULT_TEMPLATE_SPECIFICATION_IMPORT_LIST_STUDENT:
    'DEFAULT_TEMPLATE_SPECIFICATION_IMPORT_LIST_STUDENT',
  DEFAULT_TEMPLATE_SPECIFICATION_IMPORT_SINGLE_STUDENT:
    'DEFAULT_TEMPLATE_SPECIFICATION_IMPORT_SINGLE_STUDENT',
};
